// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvj3_1Itqg4oTEjNDUOMjnNzR7HHLMUPY',
    appId: '1:21496548710:web:0220662f4f669b64ba0ca7',
    messagingSenderId: '21496548710',
    projectId: 'cybernews-3291a',
    authDomain: 'cybernews-3291a.firebaseapp.com',
    storageBucket: 'cybernews-3291a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfk_9nJs1iele0H_JWjK9MeO6nQcrJqok',
    appId: '1:21496548710:android:fc8e3f733d212196ba0ca7',
    messagingSenderId: '21496548710',
    projectId: 'cybernews-3291a',
    storageBucket: 'cybernews-3291a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPWGUlap0yuRpl2CqN88wfeM9y2xrxkQ',
    appId: '1:21496548710:ios:15782168637ffeb6ba0ca7',
    messagingSenderId: '21496548710',
    projectId: 'cybernews-3291a',
    storageBucket: 'cybernews-3291a.appspot.com',
    iosBundleId: 'com.example.cyberNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPWGUlap0yuRpl2CqN88wfeM9y2xrxkQ',
    appId: '1:21496548710:ios:1b74511c218698f7ba0ca7',
    messagingSenderId: '21496548710',
    projectId: 'cybernews-3291a',
    storageBucket: 'cybernews-3291a.appspot.com',
    iosBundleId: 'com.example.cyberNews.RunnerTests',
  );
}
